name: Sync product-management to bowfes-ecom

on:
  push:
    paths:
      - 'product-management/**'   # Trigger khi có thay đổi trong thư mục này
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3

      - name: Copy product-management into new repo structure
        run: |
          mkdir sync-folder
          cp -r product-management/* sync-folder/
          cd sync-folder
          git init -b main
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Sync from BowfEs/product-management"


      - name: Push to bowfes-ecom
        env:
          TOKEN: ${{ secrets.BOWFES_ECOM }}
        run: |
          cd sync-folder
          git remote add target https://x-access-token:${TOKEN}@github.com/Presceltooo/bowfes-ecom.git
          git push --force target main  
