name: Sync product-management to bowfes-ecom

on:
  push:
    paths:
      - 'product-management/**'
    branches:
      - main  # hoặc tên branch chính của bạn

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # quan trọng để lấy toàn bộ history

      - name: Split subtree
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Tạo branch tạm chứa commit subtree
          git subtree split --prefix=product-management -b ecom-sync

      - name: Push to target repo (bowfes-ecom)
        env:
          REPO_URL: https://x-access-token:${{ secrets.TARGET_REPO_TOKEN }}@github.com/<YOUR_USERNAME>/bowfes-ecom.git
        run: |
          git push --force $REPO_URL ecom-sync:main
