name: Sync product-management to bowfes-ecom

on:
  push:
    paths:
      - 'product-management/**'   # Trigger khi có thay đổi trong thư mục này
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Quan trọng! Phải fetch toàn bộ lịch sử để subtree hoạt động

      - name: Create subtree branch
        run: |
          git subtree split --prefix=product-management -b split-branch

      - name: Push to bowfes-ecom
        env:
          TOKEN: ${{ secrets.BOWFES_ECOM }}
        run: |
          git remote add target https://x-access-token:${TOKEN}@github.com/Presceltooo/bowfes-ecom.git
          git push --force target split-branch:main
