name: Sync Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Clone source repo
        uses: actions/checkout@v3

      - name: Push to target repo
        run: |
          git config --global user.name "D.T.C"
          git config --global user.email "a01672034597@gmail.com"

          # Thêm remote target dùng secret chứa token
          git remote add target https://${{ secrets.BOWFES_ECOM }}@github.com/Presceltooo/bowfes-ecom.git

          # Đẩy code lên repo target
          git push --force target main
