name: Sync product-management to bowfes-ecom

on:
  push:
    paths:
      - 'product-management/**'   # Kích hoạt khi có thay đổi trong thư mục này
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full source repo (BowfEs)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Quan trọng để lấy đủ lịch sử cho subtree

      - name: Push subtree (product-management) to bowfes-ecom
        env:
          TOKEN: ${{ secrets.BOWFES_ECOM }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Tạo branch từ subtree
          git subtree split --prefix=product-management -b sync-branch

          # Push subtree branch lên repo đích
          git push --force https://x-access-token:${TOKEN}@github.com/Presceltooo/bowfes-ecom.git sync-branch:main
